### PR TITLE
Fixed pom.xml

### PR DESCRIPTION
**Pull request by TTRCharlie**
Somethings are missed from pom.xml file due to the jar file is couldn't run

### CODE REVIEW

**Comment by KoxSosen** [comment]
I will review this tomorrow, thank you for your contribution!

**Comment by KoxSosen** [comment]
Please re base your pr on the new changes. ( pom.xml )

**Comment by TTRCharlie** [comment]
Done

**Comment by KoxSosen** [comment]
Please rebase your pr again. Do note that there will be new libs added to the pom.xml file soon to assist with the web search & the cat command.

**Comment by TTRCharlie** [comment]
I did it recently

**Pull request closed without merging**
